### ISSUE TITLE
installation/arch.rst: Missing bullet point?

### ISSUE THREAD

**Issue by camoz** [linrunner/tlp-doc#13]
Hi,

in `installation/arch.rst`, could it be that there is a bullet point missing for `acpi_call` (withouth `-lts`)?

**Comment by linrunner** [comment]
_acpi-call_ is not needed anymore. This is explained in the "important" box above.

**Comment by camoz** [comment]
Ah sorry, forgot that this section only applies to archlinux and they only have the latest kernel in the repo...
