### ISSUE TITLE
TLP vs. KDE Plasma 6 compatibility

### ISSUE THREAD

**Issue by jpetso** [linrunner/tlp-doc#20]
Hi, just a quick note that Plasma 6.0 dropped wireless power savings settings from its power profiles. Meaning they won't change automatically anymore, the only place to turn wireless devices on and off is through direct user interaction in the Networks or Bluetooth applets.

I'm not sure if that matters for [your FAQ on the topic](https://linrunner.de/tlp/faq/settings.html#faq-set-desktop-conflict), but I thought I'll leave a note in case it makes a difference. Cheers!

**Comment by linrunner** [comment]
Done. Thanks.
