### ISSUE TITLE
Battery thresholds page: two instances of CHARGE_TRESH instead of CHARGE_THRESH

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linrunner/tlp-doc#6]
[This page](https://linrunner.de/tlp/settings/battery.html) has:

>     Charging starts upon connecting AC power, but only if the battery charge level is below the start threshold (START_CHARGE_TRESH_BATx); it will not charge when the level is above the start threshold
> 
>     Charging stops when reaching the stop threshold (STOP_CHARGE_TRESH_BATx)

But later the page says:

```
START_CHARGE_THRESH_BAT0=75
STOP_CHARGE_THRESH_BAT0=100
```
And I think it is the spelling in this latter case - i.e. 'THRESH', with an 'H' - that is correct. Worryingly, though, with neither spelling ('TRESH' or 'THRESH') does tlp display an error when it (tlp) is run in a terminal.

**Comment by linrunner** [comment]
Fixed, thanks. The ultimate reference is always /etc/tlp.conf.
