### ISSUE TITLE
Fedora rawhide

### ISSUE THREAD

**Issue by mgarofano80** [linrunner/tlp-doc#9]
Hi! Could you please update the repo to make it work under Fedora rawhide? i forced the repo to work and I can report tlp works in rawhide with no issues for me.

**Comment by linrunner** [comment]
Hi,

this issue tracker is intended exclusively for corrections to TLP's documentation website. Please keep this in mind in the future.

Regarding your question: the packages tlp, tlp-rdw come directly from the Fedora repos, no need for action here. 

If you mean the ThinkPad kernel packages (akmods): you can take the repo as is or leave it alone. An extension to rawhide is not planned.
